#!/usr/bin/env python

import sys
import ramirez.mcore.events
import ramirez.mcore.trace

if __name__ == '__main__' :
	name = sys.argv[1]
	hours = int(sys.argv[2])
	tr = ramirez.mcore.trace.Trace(name, "%s.db" % name, 60000, 1000, 0)

	end = ramirez.mcore.events.tick()
	start = end - 3600*1000 * hours
	for t in tr.read(start, end).result() :
		print t
