#!/usr/bin/env python

import json
import sys
import zmq

# TODO write a subscribe-many send-one zmq thing.
# TODO come up with a storage layer for heatmap to use
# TODO answer the rest of the pending questions in the heatmap github issue (#29)

if __name__ == '__main__' :
	zmq_url = sys.argv[1]

	c = zmq.Context(1)
	s = c.socket(zmq.SUB)
	s.connect(zmq_url)
	s.setsockopt (zmq.SUBSCRIBE, "")

	while True :
		r, w, x = zmq.core.poll.select([s], [], [], 0.1)
		if r :
			msg = s.recv()
			msg = json.loads(msg)

			# TODO should I track how 'bursty' the busyness of a cell is, or that not matter?  How would that even be done?  Should this script run open-ended and have a separate script, or run for protracted amounts of time and produce a static image at the end?

			b = 0
			for c in msg["busy_cells"] :
				for v in c :
					if v :
						b += 1

			print 'busy %d/2048' % b
